version: 2.1
orbs:
  # To install the required node version
  node: circleci/node@5.0.3
jobs:
  build:
    # No. of servers/machines
    parallelism: 1
    docker:
      - image: cimg/ruby:3.3.5-node
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "18.12"
      # - run: node --version
      # - run: gem install bundler:2.2.20
      # # install postgresql dependency
      # - run: sudo apt update && sudo apt install postgresql-client
      - run:
          name: Install dependencies
          command: |
            sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev
      - run:
          name: Bundle install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: Yarn install
          command: yarn install --cache-folder vendor/node_modules
      - run:
          name: Run Rubocop
          command: bundle exec rubocop
      - run:
          name: Lint JS and JSON
          command: npx eslint "./app/javascript/src/**/*.{js,jsx,json}"
      - run:
          name: Setup database
          command: cp config/database.yml.ci config/database.yml
      - run:
          name: Create and load database schema
          command: bundle exec rails db:create db:schema:load --trace
      - run:
          name: Generate assets
          command: chmod a+x ./bin/webpacker && ./bin/webpacker
      - run:
          name: Compile assets
          command: bundle exec rails webpacker:compile

workflows:
  version: 2
  commit:
    jobs:
      - build
